name: Gatsby Publish

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Publish Title'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          deploy-repo: enpitsuLin.github.io
